#!/usr/bin/env bash
# =============================================================================
# ANNOTATION GUIDE — MASTER WORKFLOW
# =============================================================================
# This file is the one-command entry point for the entire project.
#
# What it does, in order:
#   1. Resolves the repository root from the location of this script.
#   2. Creates a log directory and records the complete run in logs/run_all.log.
#   3. Records a wall-clock start time for reporting only.
#   4. Calls setup.sh so the exact project environment exists before analysis.
#   5. Removes generated data/, tmp/, results/, and the current CHECKSUMS.txt.
#      This intentionally prevents a new run from accidentally reusing old
#      scientific outputs.
#   6. Recreates the minimal generated-directory structure.
#   7. Copies software_versions.tsv into results/ so environment provenance is
#      part of the checksummed scientific result set.
#   8. Runs Steps 1–6 in their required order.
#   9. Checks that every required major output exists and is non-empty.
#  10. Reports total elapsed runtime.
#
# Important reproducibility point:
#   CHECKSUMS.reference.txt is NOT deleted here. It is the fixed reference
#   manifest. CHECKSUMS.txt is regenerated by every scientific run.
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${ROOT}"
mkdir -p logs
LOG="${ROOT}/logs/run_all.log"
exec > >(tee "${LOG}") 2>&1
START="$(date +%s)"

echo "============================================================"
echo "FOL4287 FIVE-GENOME MINIMAP2 SYNTENY PIPELINE"
echo "============================================================"

bash setup.sh

rm -rf data tmp results
rm -f CHECKSUMS.txt
mkdir -p data/raw data/analysis tmp results
cp software_versions.tsv results/software_versions.tsv

bash scripts/01_download_genomes.sh
bash scripts/02_run_minimap2.sh
bash scripts/03_summarize_multigenome.sh
bash scripts/04_plot_summary.sh
bash scripts/05_plot_circos.sh
bash scripts/06_checksums.sh

REQUIRED=(
  "results/software_versions.tsv"
  "results/genome_metadata.tsv"
  "results/pairwise_alignments/Fol4287_vs_Fo47.tsv"
  "results/pairwise_alignments/Fol4287_vs_FoCL57.tsv"
  "results/pairwise_alignments/Fol4287_vs_FoCotton.tsv"
  "results/pairwise_alignments/Fol4287_vs_FolD11.tsv"
  "results/pairwise_summary.tsv"
  "results/multigenome_chromosome_synteny.tsv"
  "results/percent_aligned_matrix.tsv"
  "results/core_vs_lineage_specific_by_query.tsv"
  "results/chromosome_across_query_summary.tsv"
  "results/Fol4287_multigenome_heatmap.svg"
  "results/core_vs_lineage_specific_by_query.svg"
  "results/Fol4287_vs_Fo47_circos.svg"
  "CHECKSUMS.txt"
)
for file in "${REQUIRED[@]}"; do
  [[ -s "${file}" ]] || { echo "ERROR: required output missing: ${file}"; exit 1; }
done

END="$(date +%s)"
ELAPSED="$((END-START))"
echo "============================================================"
echo "PIPELINE COMPLETE"
echo "Runtime: $((ELAPSED/60)) min $((ELAPSED%60)) sec"
echo "============================================================"
